const actors = [
  {
    actName: "Victoria Justice",
    charId: 1,
    portrays: "Tori Vega",
    age: 29,
  },
  {
    actName: "Leon Thomas III",
    charId: 2,
    portrays: "Andre Harris",
    age: 29,
  },
  {
    actName: "Elizabeth Gillies",
    charId: 3,
    portrays: "Jade West",
    age: 29,
  },
  {
    actName: "Avan Jogia",
    charId: 4,
    portrays: "Beck Oliver",
    age: 31,
  },
  {
    actName: "Matt Bennett",
    charId: 5,
    portrays: "Robbie Shapiro",
    age: 31,
  },
  {
    actName: "Ariana Grande",
    charId: 6,
    portrays: "Cat Valentine",
    age: 29,
  },
  {
    actName: "Jake Farrow",
    charId: 7,
    portrays: "Rex Powers",
    age: 50,
  },
  {
    actName: "Daniella Monet",
    charId: 8,
    portrays: "Trina Vega",
    age: 33,
  },
  {
    actName: "Michael Eric Reid",
    charId: 9,
    portrays: "Sinjin Van Cleef",
    age: 30,
  },
  {
    actName: "Eric Lange",
    charId: 10,
    portrays: "Erwin Sikowitz",
    age: 49,
  },
  {
    actName: "Lane Napper",
    charId: 11,
    portrays: "Lane Alexander",
    age: 55,
  },
  {
    actName: "Jim Pirri",
    charId: 12,
    portrays: "David Vega",
    age: 55,
  },
  {
    actName: "Jennifer Carta",
    charId: 13,
    portrays: "Holly Vega",
    age: 52,
  },
  {
    actName: "Marilyn Harris Smith",
    charId: 14,
    portrays: "Charlotte Harris",
    age: 67,
  },
  {
    actName: "Susan Chuang",
    charId: 15,
    portrays: "Mrs. Lee",
    age: 48,
  },
  {
    actName: "Ryan Rottman",
    charId: 16,
    portrays: "Ryder Daniels",
    age: 38,
  },
  {
    actName: "Yvette Nicole Brown",
    charId: 17,
    portrays: "Helen Dubois",
    age: 51,
  },
];
