const characters = [
  {
    charName: "Tori Vega",
    charId: 1,
    type: "Main",
    episodes: 57,
  },
  {
    charName: "Andre Harris",
    charId: 2,
    type: "Main",
    episodes: 57,
  },
  {
    charName: "Jade West",
    charId: 3,
    type: "Main",
    episodes: 57,
  },
  {
    charName: "Beck Oliver",
    charId: 4,
    type: "Main",
    episodes: "unknown",
  },
  {
    charName: "Robbie Shapiro",
    charId: 5,
    type: "Main",
    episodes: 57,
  },
  {
    charName: "Cat Valentine",
    charId: 6,
    type: "Main",
    episodes: "unknown",
  },
  {
    charName: "Rex Powers",
    charId: 7,
    type: "Main",
    episodes: "Unknown",
  },
  {
    charName: "Trina Vega",
    charId: 8,
    type: "Main",
    episodes: "unknown",
  },
  {
    charName: "Sinjin Van Cleef",
    charId: 9,
    type: "Recurring",
    episodes: "unknown",
  },
  {
    charName: "Erwin Sikowitz",
    charId: 10,
    type: "Recurring",
    episodes: 28,
  },
  {
    charName: "Lane Alexander",
    charId: 11,
    type: "Recurring",
    episodes: 20,
  },
  {
    charName: "David Vega",
    charId: 12,
    type: "Recurring",
    episodes: 16,
  },
  {
    charName: "Holly Vega",
    charId: 13,
    type: "Recurring",
    episodes: 14,
  },
  {
    charName: "Charlotte Harris",
    charId: 14,
    type: "Recurring",
    episodes: 7,
  },
  {
    charName: "Mrs. Lee",
    charId: 15,
    type: "Recurring",
    episodes: 4,
  },
  {
    charName: "Ryder Daniels",
    charId: 16,
    type: "Other",
    episodes: 1,
  },
  {
    charName: "Helen Dubois",
    charId: 17,
    type: "Other",
    episodes: 1,
  },
];
